**Aim:** To implement ANN Model on Iris dataset.

**ANN MODEL:**

The term "Artificial neural network" refers to a biologically inspired sub-field of artificial intelligence modeled after the brain. An Artificial neural network is usually a computational network based on biological neural networks that construct the structure of the human brain. Similar to a human brain has neurons interconnected to each other, artificial neural networks also have neurons that are linked to each other in various layers of the networks. These neurons are known as nodes.

Artificial neural network tutorial covers all the aspects related to the artificial neural network. In this tutorial, we will discuss ANNs, Adaptive resonance theory, Kohonen self-organizing map, Building blocks, unsupervised learning, Genetic algorithm, etc.

An Artificial Neural Network in the field of Artificial intelligence where it attempts to mimic the network of neurons makes up a human brain so that computers will have an option to understand things and make decisions in a human-like manner. The artificial neural network is designed by programming computers to behave simply like interconnected brain cells.

There are around 1000 billion neurons in the human brain. Each neuron has an association point somewhere in the range of 1,000 and 100,000. In the human brain, data is stored in such a manner as to be distributed, and we can extract more than one piece of this data when necessary from our memory parallelly. We can say that the human brain is made up of incredibly amazing parallel processors.

**Artificial Neural Network primarily consists of three layers:**

**Input Layer:**

As the name suggests, it accepts inputs in several different formats provided by the programmer.

**Hidden Layer:**

The hidden layer presents in-between input and output layers. It performs all the calculations to find hidden features and patterns.

**Output Layer:**

The input goes through a series of transformations using the hidden layer, which finally results in output that is conveyed using this layer.

In [ ]:
import pandas as pd
import io
data = pd.read_csv('Iris.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
import sklearn.datasets as datasets
from sklearn import preprocessing
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
normalizer = preprocessing.StandardScaler()
X_normalized = normalizer.fit_transform(X)
print(X_normalized)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler


In [ ]:
iris = datasets.load_iris()
X = iris.data

In [ ]:
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

In [ ]:
df_standardized = pd.DataFrame(data=X_standardized, columns=iris.feature_names)

In [ ]:
print(df_standardized.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444


In [ ]:
X[10:15, 2] = np.nan

In [ ]:
print("\nMissing Values After Imputation:\n", df_standardized.isnull().sum())



Missing Values After Imputation:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64


In [ ]:
import numpy as np
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [ ]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))  # Input layer with 4 features
model.add(Dense(8, activation='relu'))  # Hidden layer with 8 neurons and ReLU activation
model.add(Dense(3, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X_train, tf.keras.utils.to_categorical(y_train, num_classes=3), epochs=100, batch_size=5)

Epoch 1/100
24/24 [==============================] - 1s 3ms/step - loss: 0.9708 - accuracy: 0.2500
Epoch 2/100
24/24 [==============================] - 0s 3ms/step - loss: 0.8816 - accuracy: 0.5333
Epoch 3/100
24/24 [==============================] - 0s 2ms/step - loss: 0.8029 - accuracy: 0.6333
Epoch 4/100
24/24 [==============================] - 0s 2ms/step - loss: 0.7306 - accuracy: 0.6333
Epoch 5/100
24/24 [==============================] - 0s 3ms/step - loss: 0.6600 - accuracy: 0.6417
Epoch 6/100
24/24 [==============================] - 0s 3ms/step - loss: 0.6099 - accuracy: 0.6500
Epoch 7/100
24/24 [==============================] - 0s 2ms/step - loss: 0.5743 - accuracy: 0.6583
Epoch 8/100
24/24 [==============================] - 0s 2ms/step - loss: 0.5484 - accuracy: 0.7000
Epoch 9/100
24/24 [==============================] - 0s 2ms/step - loss: 0.5272 - accuracy: 0.7750
Epoch 10/100
24/24 [==============================] - 0s 2ms/step - loss: 0.5091 - accuracy: 0.8083
Epoch 11/

In [ ]:
_, accuracy = model.evaluate(X_test, tf.keras.utils.to_categorical(y_test, num_classes=3))
print(f'Accuracy: {accuracy * 100:.2f}%')

1/1 [==============================] - 0s 184ms/step - loss: 0.0424 - accuracy: 0.9667
Accuracy: 96.67%


ANN Model:

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from sklearn.metrics import accuracy_score, classification_report


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = Sequential()
model.add(Dense(units=16, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=3, activation='softmax'))


NameError: ignored

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])


In [ ]:
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
3/3 [==============================] - 2s 193ms/step - loss: 1.1035 - accuracy: 0.3750 - val_loss: 1.0782 - val_accuracy: 0.3333
Epoch 2/50
3/3 [==============================] - 0s 54ms/step - loss: 1.0802 - accuracy: 0.5417 - val_loss: 1.0556 - val_accuracy: 0.5000
Epoch 3/50
3/3 [==============================] - 0s 47ms/step - loss: 1.0571 - accuracy: 0.5729 - val_loss: 1.0342 - val_accuracy: 0.6250
Epoch 4/50
3/3 [==============================] - 0s 35ms/step - loss: 1.0343 - accuracy: 0.6250 - val_loss: 1.0137 - val_accuracy: 0.7083
Epoch 5/50
3/3 [==============================] - 0s 45ms/step - loss: 1.0142 - accuracy: 0.6875 - val_loss: 0.9938 - val_accuracy: 0.7500
Epoch 6/50
3/3 [==============================] - 0s 33ms/step - loss: 0.9928 - accuracy: 0.6979 - val_loss: 0.9747 - val_accuracy: 0.7500
Epoch 7/50
3/3 [==============================] - 0s 34ms/step - loss: 0.9739 - accuracy: 0.7292 - val_loss: 0.9558 - val_accuracy: 0.7500
Epoch 8/50
3/3 [==========

In [ ]:
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

1/1 [==============================] - 0s 182ms/step


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)


In [ ]:
print(f"Accuracy: {accuracy}")
print("Classification Report:\n", report)

Accuracy: 0.9333333333333333
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.78      0.88         9
           2       0.85      1.00      0.92        11

    accuracy                           0.93        30
   macro avg       0.95      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

